In [ ]:
#  Array - special variable which can hold more than one value at a time

In [8]:
import array
 # create an integer array
arr = array.array('i', [10,20,30,40,50])
print("Array:", arr)

# Access elemnet by index
print("First element:", arr[0])
print("Last element:", arr[-1])

# append a new elemnt at the ned of the array
arr.append(60)
print("After append:", arr)

#Insert a new value 25 at index position 2
arr.insert(2,25)
print("After insert:", arr)

# remove the first occurence of the value 40 from the array
arr.remove(40)
print("After remove:", arr)

# iterate over the array element and print them one by one
print("Iterating over array:")
for num in arr:
    print(num)

Array: array('i', [10, 20, 30, 40, 50])
First element: 10
Last element: 50
After append: array('i', [10, 20, 30, 40, 50, 60])
After insert: array('i', [10, 20, 25, 30, 40, 50, 60])
After remove: array('i', [10, 20, 25, 30, 50, 60])
Iterating over array:
10
20
25
30
50
60


In [ ]:
#  NumPy Library- open source python Library, contain multidiminensional array as data structure. used for numerical calculation and statistical calc.

In [10]:
# how to import numpy
import numpy as np

In [11]:
arr = np.array([1,2,3,4,5]) # create a Numpy arrray from a python list

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
# create 2-D array
arr2d = np.array([[1,2],[3,4]])
print(arr2d)

[[1 2]
 [3 4]]


In [13]:
# np.zeros()- 
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#  np.ones()
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [15]:
# np.full()
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [16]:
# np.eye
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# np.arrange(start, stop, step)function
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
# Indexing
arr = np.array([1,2,3,4])
print(arr[0])

1


In [20]:
arr = np.array([5,6,7,8])
print(arr[2] + arr[3])

15


In [22]:
# access fron 2d array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("5th element on 2nd row:", arr[1,4])

5th element on 2nd row: 10


In [ ]:
# Slicing in aarrays 
we pass slice instead of index like this: [start:end]

In [23]:
# elemnts from index 1 to index 5
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [24]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4]) # elemnts from the begining to index 4

[1 2 3 4]


In [25]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [26]:
# slicing 2d array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [27]:
# astype() - change thge data type from float to integer

arr = np.array([1.1,2.1,3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# Copy & View
copy owns the data and any changes made to copy willnot affect original array, and any changes made to the original array will not affect the copy
view does not own data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view

In [28]:
# make a copy , change the original array and display both arrays

arr = np.array([1,2,3,4,5])

# make an independent copy of array
x= arr.copy() 

# change the first element of arr to 55
arr[0] = 55

print(arr) # arr after modification
print(x) # print x to confirm it is unaffected by changes arr

[55  2  3  4  5]
[1 2 3 4 5]


In [29]:
# make a view, change the original array, and display both arrays

arr = np.array([1,2,3,4,5])

# create a new view- view() does not  create a seprate copy - it shares the same data in memory
x = arr.view()

arr[0] = 62

print(arr)
print(x)


[62  2  3  4  5]
[62  2  3  4  5]


In [30]:
# shape of array
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [31]:
# reshape array

arr = np.array([1, 2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
# join array

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [33]:
# Join 2d array along rows(axis= 1)

arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2), axis = 1)
#axis =0 - join along rows(vertically)
# axis = 1 - join along columns(horizontally)


print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [34]:
# stack() function - join two array
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.stack((arr1,arr2),axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [36]:
#np.hstack()- horizontal stack- stack along rows
# np.vstack() - vertical stack- aloong column
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

#arr = np.hstack((arr1,arr2))
arr = np.vstack((arr1,arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [43]:
# array split()- reverse operation of joining
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [39]:
# Where() method - search an array for a certain value, and return the index that get a match

arr = np.array([1,2,3,4,5,4,4])

x= np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [40]:
# sort() array - putting element in ordered sequence

arr = np.array([8,5,0,1])
print(np.sort(arr))

[0 1 5 8]


In [41]:
arr = np.array(['benz', 'ford', 'alto'])
print(np.sort(arr))

['alto' 'benz' 'ford']


In [44]:
# sort 2d array
arr = np.array([[9,6,4],[3,0,1]])
print(np.sort(arr))

[[4 6 9]
 [0 1 3]]
